NPY_BOOL = 0
NPY_BYTE = 1
NPY_UBYTE = 2
NPY_SHORT = 3
NPY_USHORT = 4
NPY_INT = 5
NPY_UINT = 6
NPY_LONG = 7
NPY_ULONG = 8
NPY_LONGLONG = 9
NPY_ULONGLONG = 10
NPY_FLOAT = 11
NPY_DOUBLE = 12
NPY_LONGDOUBLE = 13
NPY_CFLOAT = 14
NPY_CDOUBLE = 15
NPY_CLONGDOUBLE = 16
NPY_OBJECT = 17
NPY_STRING = 18
NPY_UNICODE = 19
NPY_VOID = 20
NPY_DATETIME = 21
NPY_TIMEDELTA = 22
NPY_HALF = 23
NPY_NTYPES = 24
NPY_NOTYPE = 25
NPY_CHAR = 26
NPY_USERDEF = 256

NPY_BOOLLTR = '?'
NPY_BYTELTR = 'b'
NPY_UBYTELTR = 'B'
NPY_SHORTLTR = 'h'
NPY_USHORTLTR = 'H'
NPY_INTLTR = 'i'
NPY_UINTLTR = 'I'
NPY_LONGLTR = 'l'
NPY_ULONGLTR = 'L'
NPY_LONGLONGLTR = 'q'
NPY_ULONGLONGLTR = 'Q'
NPY_HALFLTR = 'e'
NPY_FLOATLTR = 'f'
NPY_DOUBLELTR = 'd'
NPY_LONGDOUBLELTR = 'g'
NPY_CFLOATLTR = 'F'
NPY_CDOUBLELTR = 'D'
NPY_CLONGDOUBLELTR = 'G'
NPY_OBJECTLTR = 'O'
NPY_STRINGLTR = 'S'
NPY_STRINGLTR2 = 'a'
NPY_UNICODELTR = 'U'
NPY_VOIDLTR = 'V'
NPY_DATETIMELTR = 'M'
NPY_TIMEDELTALTR = 'm'
NPY_CHARLTR = 'c'

NPY_INTPLTR = 'p'
NPY_UINTPLTR = 'P'

NPY_GENBOOLLTR ='b'
NPY_SIGNEDLTR = 'i'
NPY_UNSIGNEDLTR = 'u'
NPY_FLOATINGLTR = 'f'
NPY_COMPLEXLTR = 'c'

NPY_ANYORDER = -1
NPY_CORDER = 0
NPY_FORTRANORDER = 1
NPY_KEEPORDER = 2

NPY_CLIP = 0
NPY_WRAP = 1
NPY_RAISE = 2

NPY_LITTLE = '<'
NPY_BIG = '>'
NPY_NATIVE = '='
NPY_SWAP = 's'
NPY_IGNORE = '|'

import sys
if sys.byteorder == 'big':
    NPY_NATBYTE = NPY_BIG
    NPY_OPPBYTE = NPY_LITTLE
else:
    NPY_NATBYTE = NPY_LITTLE
    NPY_OPPBYTE = NPY_BIG
del sys
