# auto-generating the unsigned part of int_include.h

"""
usage:
run this script in int_include.h's folder.

Rule:
all #define OP_INT_ macros are repeated for uint,
except:
if an int macro is immediately followed by an uint
version, this takes precedence.
"""

fname = 'int_include.h'

srclines = []
lines = []

stopline = '/* no editing below this point */'

for srcline in file(fname):
    srcline = srcline.rstrip()
    line = srcline.lstrip()
    if line.startswith('#define OP_INT_') and line.find('_OVF') < 0:
        macroname = line.split('(')[0].split()[1]
        newname = 'OP_UINT_' + macroname[7:]
        lines.append('#define %s %s' % (newname, macroname))
    elif line.startswith('#define OP_UINT_'):
        # comment the last one out
        lines.append('/* skipping %s */' % lines.pop().split()[1])
    elif line == stopline:
        break
    srclines.append(srcline)

print >> file(fname, 'w'), '\n'.join(srclines + [stopline,
            '/* following lines are generated by mkuint.py */', ''] + lines)
