
// We hand craft these in module/support.ll
char *RPyString_AsString(RPyString*);
int RPyString_Size(RPyString*);
RPyString *RPyString_FromString(char *);

void raisePyExc_IOError(char *);
void raisePyExc_ValueError(char *);
void raisePyExc_OverflowError(char *);
void raisePyExc_ZeroDivisionError(char *);
void raisePyExc_RuntimeError(char *);
#define RPyRaiseSimpleException(exctype, errormsg) raise##exctype(errormsg)

// Generated by rpython - argggh have to feed in prototypes
RPyFREXP_RESULT *ll_frexp_result(double, int);
RPyMODF_RESULT *ll_modf_result(double, double);
RPySTAT_RESULT *ll_stat_result(int, int, int, int, int, int, int, int, int, int);
void RPYTHON_RAISE_OSERROR(int error);

#include <errno.h>
#include <locale.h>
#include <ctype.h>

//the placeholder in the next line gets replaced by the actual python.h path
#include __PYTHON_H__

// overflows/zeros/values raising operations
__RAISING_OP__

// Append some genc files here manually from python
