# A basic workflow to run pre-commit on code changes.
# https://pre-commit.com and https://github.com/pre-commit/action

name: pre-commit

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main", "py3.11" ]
  pull_request:
    branches: [ "main", "py3.11" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.1
